"""Constants shared by the repository-local Codex semantic MVP."""

OFF_MODE = "off"
SHADOW_MODE = "shadow"
ACTIVE_MODE = "active"

STATE_DIR_ENV = "HMASD_CODEX_MVP_STATE_DIR"
KILL_SWITCH_ENV = "HMASD_CODEX_MVP_DISABLE"

RETURN_START = "<HMASD_SUBAGENT_RETURN_V1>"
RETURN_END = "</HMASD_SUBAGENT_RETURN_V1>"

MAX_RAW_MESSAGE_BYTES = 1_000_000
MAX_TYPED_JSON_BYTES = 32_768
MAX_WAIT_SECONDS = 1500
WAIT_POLL_SECONDS = 0.5

ALWAYS_ON_SCOPE = "session"
ALWAYS_ON_OBJECTIVE = "always-on managed semantic session"

