#!/usr/bin/env python3
"""Outcome-free n selection for ``UCOPE-B-EXPLORE-COMPETENCE-WHITENED-R01``.

Uses **only** the exact normal-equation solve — the reference arm — with no learner, no
optimizer and no competence claim about any learner. For each tail-row budget on the frozen
geometric grid it asks two questions per policy:

* does the exact tail solve, fed through the frozen root target package and solved exactly,
  recover the oracle root vector? and
* is ``d_objective = max|beta_tail_star - beta*|`` at most ``0.10``?

The smallest grid point at which both hold for all six policies is the ``n`` the competence
object then fixes, before any learner runs.

Index law
---------
Rows are generated by the frozen host at episode indices ``i = OFFSET + j`` with
``OFFSET = 1_000_000`` and ``j = 0 .. m-1``. Every published UCOPE run draws from
``0 .. 5_119`` (B1, both ladders, both R02 rungs) or ``0 .. 319`` (ASSESS), so the ranges are
disjoint and, because every host draw is counter-addressed on
``(namespace, seed, episode_index, counter)``, so are the draws. ``OFFSET`` is a multiple of
20, so the frozen 10-episode behaviour stratum (``host.behavior_stratum``, ``index % 10``) and
the 20-episode fold alternation (``host.group_fold``, ``(index // 10) % 2``) start in exactly
the phase they have at index 0.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import subprocess
import sys
import time
from typing import Any, Sequence

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from fractions import Fraction  # noqa: E402

from experiments.candidates.ucope.competence_first_scout_r01.contract import (  # noqa: E402
    B1_SEEDS,
    CONTEXTS,
    K_EVAL,
    K_TRAIN,
    context_id,
)
from experiments.candidates.ucope.competence_first_scout_r01.host import (  # noqa: E402
    behavior_stratum,
    execute_policy_episode,
    group_fold,
)
from experiments.candidates.ucope.competence_first_scout_r01.model import (  # noqa: E402
    root_basis,
    tail_basis,
)
from experiments.candidates.ucope.competence_first_scout_r01.oracle import (  # noqa: E402
    build_oracle,
    posterior_short,
)

OBJECT_ID = "UCOPE-B-EXPLORE-COMPETENCE-WHITENED-R01"
RECORD_FORMAT = "UCOPE_COMPETENCE_WHITENED_R01_N_SELECTION_V1"
RESOURCE_PREFLIGHT = PROJECT_ROOT / "scripts/hmasd_resource_preflight.py"
MINIMUM_MEMORY_BYTES = 4 * 1024**3

OFFSET = 1_000_000
BETA_STAR = (0.31, 0.60, 1.35, -1.08, -0.891)
D_OBJECTIVE_CEILING = 0.10
# Tail rows per policy. A policy's tail rows are the complementary fold's PROBE rows, which is
# one quarter of that seed's generated rows, so m episodes per context give 2m tail rows.
TAIL_ROW_GRID = tuple(10_240 * factor for factor in (1, 2, 4, 8, 16))


class SelectionRefusal(RuntimeError):
    """Raised before stateful work when a launch condition fails."""


def _numpy():
    import numpy

    return numpy


def admit_memory(receipt: Path) -> dict[str, Any]:
    receipt.parent.mkdir(parents=True, exist_ok=True)
    completed = subprocess.run(
        [sys.executable, str(RESOURCE_PREFLIGHT), "admit-memory", "--out", str(receipt)],
        cwd=PROJECT_ROOT, capture_output=True, text=True,
    )
    if completed.returncode != 0 or not receipt.is_file():
        raise SelectionRefusal(f"memory admission failed rc={completed.returncode}: {completed.stderr.strip()}")
    value = json.loads(receipt.read_text(encoding="utf-8"))
    if (
        value.get("passed") is not True
        or int(value.get("available_physical_bytes", 0)) < MINIMUM_MEMORY_BYTES
        or int(value.get("effective_available_bytes", 0)) < MINIMUM_MEMORY_BYTES
    ):
        raise SelectionRefusal("memory admission refused the launch")
    return value


def generate_columns(seed_id: str, episodes_per_context: int):
    """Stream the frozen host at fresh indices into flat numeric columns."""
    numpy = _numpy()
    count = episodes_per_context * len(CONTEXTS)
    fold = numpy.empty(count, dtype=numpy.int8)
    probe = numpy.empty(count, dtype=bool)
    belief = numpy.empty(count, dtype=numpy.float64)
    period = numpy.empty(count, dtype=numpy.int16)
    tail_return = numpy.empty(count, dtype=numpy.float64)
    probe_primitive = numpy.empty(count, dtype=numpy.float64)
    cost = numpy.empty(count, dtype=numpy.float64)
    linked = numpy.empty(count, dtype=bool)
    reliability = numpy.empty(count, dtype=numpy.float64)
    order = numpy.empty(count, dtype=numpy.int64)

    position = 0
    for offset in range(episodes_per_context):
        index = OFFSET + offset
        action, chosen = behavior_stratum(index)
        row_fold = group_fold(index)
        is_probe = action == "PROBE"
        for context in CONTEXTS:
            link, p, context_cost = context
            execution = execute_policy_episode(
                context, ancestry=(seed_id,), episode_index=index, root_action=action,
                immediate_period=chosen if not is_probe else None,
                tail_selector=(lambda _count, chosen=chosen: chosen) if is_probe else None,
                evaluation=False,
            )
            displayed = execution.displayed_short_count
            row_belief = posterior_short(link, p, displayed) if displayed is not None else Fraction(1, 2)
            fold[position] = row_fold
            probe[position] = is_probe
            belief[position] = float(row_belief)
            period[position] = chosen
            tail_return[position] = float(
                execution.tail_service + execution.tail_time + execution.tail_energy
            )
            probe_primitive[position] = float(
                execution.probe_service + execution.probe_time + execution.probe_energy
            )
            cost[position] = float(context_cost)
            linked[position] = link == "LINKED"
            reliability[position] = float(p)
            order[position] = offset
            position += 1
    return {
        "fold": fold, "probe": probe, "belief": belief, "period": period,
        "tail_return": tail_return, "probe_primitive": probe_primitive,
        "cost": cost, "linked": linked, "reliability": reliability, "episode_order": order,
    }


def _tail_design(columns, mask):
    numpy = _numpy()
    beliefs = columns["belief"][mask]
    periods = columns["period"][mask].astype(numpy.float64)
    k = periods / 9.0
    design = numpy.stack(
        [numpy.ones_like(k), beliefs, k, beliefs * k, k * k], axis=1
    )
    return design, columns["tail_return"][mask]


def _root_design(columns, mask):
    numpy = _numpy()
    probe = columns["probe"][mask].astype(numpy.float64)
    periods = columns["period"][mask].astype(numpy.float64)
    k = numpy.where(probe > 0.0, 0.0, periods / 9.0)
    cost = columns["cost"][mask]
    linked = columns["linked"][mask].astype(numpy.float64)
    reliability = columns["reliability"][mask]
    return numpy.stack([
        numpy.ones_like(k), (1.0 - probe) * k, (1.0 - probe) * k * k,
        probe, probe * cost, probe * linked, probe * linked * reliability,
    ], axis=1)


def _root_targets(columns, mask, beta_tail):
    """The frozen target package: probe_primitive + max over K_TRAIN of Q_tail."""
    numpy = _numpy()
    beliefs = columns["belief"][mask]
    candidates = []
    for train_period in K_TRAIN:
        k = train_period / 9.0
        candidates.append(
            beta_tail[0] + beta_tail[1] * beliefs + beta_tail[2] * k
            + beta_tail[3] * beliefs * k + beta_tail[4] * k * k
        )
    best = numpy.max(numpy.stack(candidates, axis=1), axis=1)
    probe = columns["probe"][mask]
    return numpy.where(probe, columns["probe_primitive"][mask] + best, columns["tail_return"][mask])


def implied_root_actions(beta_root) -> dict[str, str]:
    actions = {}
    for context in CONTEXTS:
        link, reliability, cost = context
        labels = ("PROBE", *(f"IMMEDIATE:{value}" for value in K_EVAL))
        bases = [root_basis(action_probe=True, period=0, cost=float(cost), linked=link == "LINKED", reliability=float(reliability))]
        bases += [
            root_basis(action_probe=False, period=value, cost=float(cost), linked=link == "LINKED", reliability=float(reliability))
            for value in K_EVAL
        ]
        values = [sum(c * e for c, e in zip(beta_root, basis)) for basis in bases]
        ranked = sorted((value, -index, label) for index, (label, value) in enumerate(zip(labels, values)))
        actions[context_id(context)] = "PROBE" if ranked[-1][2] == "PROBE" else "IMMEDIATE"
    return actions


def evaluate_grid(columns_by_seed, oracle_vector) -> list[dict[str, Any]]:
    numpy = _numpy()
    table = []
    for tail_rows in TAIL_ROW_GRID:
        episodes_per_context = tail_rows // 2
        policies = []
        for seed in B1_SEEDS:
            columns = columns_by_seed[seed]
            within = columns["episode_order"] < episodes_per_context
            for fold in (0, 1):
                tail_mask = within & (columns["fold"] == (1 - fold)) & columns["probe"]
                root_mask = within & (columns["fold"] == fold)
                design, targets = _tail_design(columns, tail_mask)
                beta_tail, *_ = numpy.linalg.lstsq(design, targets, rcond=None)
                gram = design.T @ design / design.shape[0]
                eigenvalues = numpy.linalg.eigvalsh(gram)
                root_design = _root_design(columns, root_mask)
                root_targets = _root_targets(columns, root_mask, beta_tail)
                beta_root, *_ = numpy.linalg.lstsq(root_design, root_targets, rcond=None)
                actions = implied_root_actions([float(value) for value in beta_root])
                policies.append({
                    "seed_id": seed,
                    "fold_id": fold,
                    "tail_rows": int(design.shape[0]),
                    "root_rows": int(root_design.shape[0]),
                    "beta_tail_star": [float(value) for value in beta_tail],
                    "d_objective": float(numpy.abs(beta_tail - numpy.asarray(BETA_STAR)).max()),
                    "gram_condition_number": float(eigenvalues.max() / eigenvalues.min()),
                    "gram_smallest_eigenvalue": float(eigenvalues.min()),
                    "implied_root_actions": actions,
                    "oracle_root_match": actions == oracle_vector,
                })
        table.append({
            "tail_rows_per_policy": tail_rows,
            "episodes_per_context": episodes_per_context,
            "policies": policies,
            "max_d_objective": max(row["d_objective"] for row in policies),
            "d_objective_all_within_ceiling": all(
                row["d_objective"] <= D_OBJECTIVE_CEILING for row in policies
            ),
            "oracle_root_matches": sum(row["oracle_root_match"] for row in policies),
            "oracle_root_all_six": all(row["oracle_root_match"] for row in policies),
        })
    return table


def run_selection(output_root: str | Path) -> Path:
    numpy = _numpy()
    output = Path(output_root).resolve()
    if output.exists():
        raise SelectionRefusal(f"output root is create-once: {output}")
    output.mkdir(parents=True)
    admission = admit_memory(output / "preflight.json")
    started = {"wall": time.perf_counter(), "cpu": time.process_time()}

    largest = max(TAIL_ROW_GRID) // 2
    columns_by_seed = {}
    for seed in B1_SEEDS:
        columns_by_seed[seed] = generate_columns(seed, largest)
        # Structural invariants of the frozen strata, asserted directly because
        # host.validate_population is written for the index range 0..episodes_per_context-1.
        columns = columns_by_seed[seed]
        if int(columns["fold"].sum()) * 2 != columns["fold"].size:
            raise SelectionRefusal("fold balance broken at the fresh index range")
        if int(columns["probe"].sum()) * 2 != columns["probe"].size:
            raise SelectionRefusal("behaviour stratum balance broken at the fresh index range")
        counts = numpy.unique(columns["period"], return_counts=True)
        if sorted(int(value) for value in counts[0]) != sorted(K_TRAIN):
            raise SelectionRefusal("training period support broken at the fresh index range")
        if len(set(int(value) for value in counts[1])) != 1:
            raise SelectionRefusal("training period balance broken at the fresh index range")

    oracle_vector = {cell: row["action"] for cell, row in build_oracle().items()}
    table = evaluate_grid(columns_by_seed, oracle_vector)
    chosen = next(
        (row["tail_rows_per_policy"] for row in table
         if row["d_objective_all_within_ceiling"] and row["oracle_root_all_six"]),
        None,
    )
    record = {
        "format": RECORD_FORMAT,
        "schema_version": 1,
        "object_id": OBJECT_ID,
        "purpose": "outcome-free n selection; exact normal-equation solve only, no learner",
        "index_law": {
            "offset": OFFSET,
            "law": "episode index i = OFFSET + j for j = 0 .. m-1",
            "published_ranges_avoided": ["0..5119 (B1, ladders, R02 rungs)", "0..319 (ASSESS)"],
            "offset_is_multiple_of_20": OFFSET % 20 == 0,
        },
        "beta_star": list(BETA_STAR),
        "d_objective_ceiling": D_OBJECTIVE_CEILING,
        "tail_row_grid": list(TAIL_ROW_GRID),
        "oracle_root_actions": oracle_vector,
        "admission": admission,
        "table": table,
        "chosen_tail_rows_per_policy": chosen,
        "chosen_episodes_per_context": (chosen // 2) if chosen else None,
        "wall_seconds": time.perf_counter() - started["wall"],
        "cpu_seconds": time.process_time() - started["cpu"],
    }
    destination = output / "n-selection.json"
    destination.write_text(json.dumps(record, indent=2, sort_keys=True), encoding="utf-8")
    return destination


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__, allow_abbrev=False)
    commands = parser.add_subparsers(dest="command", required=True)
    run = commands.add_parser("run", allow_abbrev=False)
    run.add_argument("--output-root", required=True)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    try:
        path = run_selection(args.output_root)
        record = json.loads(Path(path).read_text(encoding="utf-8"))
        print(json.dumps({
            "path": str(path),
            "chosen_tail_rows_per_policy": record["chosen_tail_rows_per_policy"],
            "chosen_episodes_per_context": record["chosen_episodes_per_context"],
        }, sort_keys=True))
    except (OSError, ValueError, TypeError, subprocess.SubprocessError, SelectionRefusal) as exc:
        print(f"UCOPE n selection stopped: {type(exc).__name__}: {exc}", file=sys.stderr)
        return 6
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
