"""Publish deterministic Claude copies of the shared methods; development command, never a launch gate."""
from pathlib import Path
import argparse
import tomllib

ROOT = Path(__file__).resolve().parents[1]
ROLE_MAP = {
 'hmasd-reviewer':'hmasd-reviewer', 'hmasd-cm-scout':'hmasd-scout',
 'hmasd-research-scout':'hmasd-scout', 'hmasd-verifier':'hmasd-verifier',
 'hmasd-research-critic':'hmasd-research-critic',
 'hmasd-experiment-operator':'hmasd-experiment-operator',
 'hmasd-experiment-tracker':'hmasd-experiment-monitor',
 'hmasd-pro-transport':'hmasd-transport', 'hmasd-implementer':'hmasd-implementer',
}
BANNER = '<!-- Generated by tools/publish_claude_control.py; edit shared source, not this body. -->\n'
CONSTITUTION = 'docs/project/OPERATING_CONSTITUTION.md'

CLAUDE_ADAPTER = ('\nClaude adapter: return directly to the assigning session using actual native returns; '
                  'do not invent Codex collaboration tools. No child agents.\n')
TRANSPORT_ADAPTER = ('\n## Claude runtime\n\nThe Claude session is the DM. It may run these steps itself with the '
                     '`mcp__agentify-desktop__*` tools or dispatch `hmasd-pro-transport` (Sonnet) with the message, '
                     'conversation URL, direction, branch and sha. Facts return to the session, which reads the answer.\n')

# Text in the shared DM role that names Codex-only routing, with its Claude counterpart.
DM_CLAUDE_REPLACEMENTS = [
    ('Root integrates main and resolves shared dependencies; it does not ACK your steps.',
     'You also integrate your own commits into main and push immediately.'),
    ('then docs/research/RESEARCH.md (your direction must be\nactive and Codex-led)',
     'then docs/research/RESEARCH.md (your direction must be\nactive and led by the Claude session)'),
    ('an Implementer child\n(HMASDImplementer, Sol/high)', 'hmasd-implementer (Opus, high effort)'),
    ('your\nTransport child (HMASDTransport) sends it.',
     'you send\nit with the Agentify tools or dispatch hmasd-pro-transport.'),
    ('you or Operator launch with preflight && runner under agent-task\non the declared node; hand the accepted handle to your monitor (HMASDExperimentMonitor) and\nrequire MONITOR_ADOPTED before ending polling.',
     'hmasd-experiment-operator launches with preflight && runner under\nagent-task on the declared node and returns the accepted handle; dispatch hmasd-experiment-tracker\nfor one bounded observation window at a time, its first return being adoption evidence.'),
    ('send Root one paragraph:\ndirection, state, evidence or commit, next step or dependency and its owner.',
     'write one NOTES.md entry and update the\nRESEARCH.md standing line: state, evidence or commit, next step or dependency and its owner.'),
]


def adapt_skill(text, name):
    if name == 'hmasd-chatgpt-pro-transport':
        text += TRANSPORT_ADAPTER
    return text


def generated(root=ROOT):
    outputs = {}
    for folder in sorted((root/'.agents/skills').glob('hmasd-*')):
        for source in sorted(folder.rglob('*')):
            if not source.is_file() or '__pycache__' in source.parts:
                continue
            target = root/'.claude/skills'/source.relative_to(root/'.agents/skills')
            data = source.read_bytes()
            if source.suffix in {'.md', '.py', '.yaml', '.yml', '.json', '.toml'}:
                data = data.replace(b'\r\n', b'\n')
            if source.name == 'SKILL.md':
                text = adapt_skill(data.decode('utf-8'), folder.name)
                head, body = text.split('---', 2)[1:]
                data = ('---'+head+'---\n\n'+BANNER+body.lstrip()).encode()
            outputs[target] = data
    for native, shared in ROLE_MAP.items():
        target = root/'.claude/agents'/f'{native}.md'
        header = target.read_text(encoding='utf-8').split('---', 2)[1]
        body = tomllib.loads((root/'.codex/agents'/f'{shared}.toml').read_text(encoding='utf-8'))['developer_instructions']
        if native == 'hmasd-experiment-operator':
            body = body.replace('DM and monitor canonical addresses', 'the assigning session return identity')
            start = body.index('After acceptance send MONITOR_ADD')
            end = body.index('A pre-process failure', start)
            body = body[:start] + ("After actual acceptance return exact node/handle/source/cwd/output and observation bound to the "
                                   "session. The session dispatches its bounded tracker; do not use sibling messaging, create a "
                                   "tracker, or keep polling after returning. Preserve collection responsibility for a later "
                                   "assigned terminal collection batch.\n\n") + body[end:]
        elif native == 'hmasd-experiment-tracker':
            body = body.replace('send MONITOR_ADOPTED directly to the DM', 'return MONITOR_ADOPTED facts to the session')
            body = body.replace('Send MONITOR_TERMINAL or MONITOR_BLOCKER directly to the DM:', 'Return MONITOR_TERMINAL or MONITOR_BLOCKER to the session:')
            body = body.replace('Reuse through followup_task for later handles.', 'The session may resume a bounded observation window for later handles.')
        elif native == 'hmasd-pro-transport':
            body = body.replace('return facts to the DM.', 'return facts to the session.')
            body = body.replace('Later questions reuse this child.', 'Later questions may reuse this agent.')
        adapter = CLAUDE_ADAPTER
        if native == 'hmasd-experiment-tracker':
            adapter += 'Observe one bounded window; return adoption/terminal evidence and pending notice state. The session resumes a later window; no standing polling service.\n'
        outputs[target] = ('---'+header+'---\n\n'+BANNER+body+adapter).encode()
    dm = tomllib.loads((root/'.codex/agents/hmasd-direction-manager.toml').read_text(encoding='utf-8'))['developer_instructions']
    for old, new in DM_CLAUDE_REPLACEMENTS:
        if old not in dm:
            raise SystemExit(f'DM role text changed; update DM_CLAUDE_REPLACEMENTS for: {old[:60]!r}')
        dm = dm.replace(old, new)
    outputs[root/'.claude/skills/hmasd-research-hub/SKILL.md'] = (f'''---
name: hmasd-research-hub
description: Drive one direction as the Claude DM under {CONSTITUTION}; not for status or mechanical edits.
---

''' + BANNER + f'The Claude session is the DM for one direction at a time under `{CONSTITUTION}`; there is no Root/DM '
    'split on this runtime. Only hmasd-experiment-operator launches result-bearing commands.\n\n## Direction ownership\n\n' + dm).encode()
    transport = outputs[root/'.claude/skills/hmasd-chatgpt-pro-transport/SKILL.md'].decode()
    transport = transport.replace('name: hmasd-chatgpt-pro-transport', 'name: hmasd-pro-transport', 1)
    # Alias includes the full method; reference paths resolve to the generated canonical copy.
    transport = transport.replace('(references/', '(../hmasd-chatgpt-pro-transport/references/')
    outputs[root/'.claude/skills/hmasd-pro-transport/SKILL.md'] = transport.encode()
    return outputs


def publish(root=ROOT, check=False):
    drift = []
    for path, data in generated(root).items():
        if not path.exists() or path.read_bytes() != data:
            drift.append(path.relative_to(root).as_posix())
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(data)
    return drift


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    changes = publish(check=args.check)
    print(('drift: ' if args.check else 'published: ') + str(len(changes)))
    if args.check and changes:
        print('\n'.join(changes))
        raise SystemExit(1)
