"""Publish deterministic Claude copies of the shared methods; development command, never a launch gate."""
from pathlib import Path
import argparse
import tomllib

ROOT = Path(__file__).resolve().parents[1]
ROLE_MAP = {
 'hmasd-reviewer':'hmasd-reviewer', 'hmasd-cm-scout':'hmasd-scout',
 'hmasd-research-scout':'hmasd-scout', 'hmasd-verifier':'hmasd-verifier',
 'hmasd-research-critic':'hmasd-research-critic',
 'hmasd-experiment-operator':'hmasd-experiment-operator',
 'hmasd-experiment-tracker':'hmasd-experiment-monitor',
 'hmasd-pro-transport':'hmasd-transport', 'hmasd-implementer':'hmasd-implementer',
}
BANNER = '<!-- Generated by tools/publish_claude_control.py; edit shared source, not this body. -->\n'
CONSTITUTION = 'docs/project/OPERATING_CONSTITUTION.md'

CLAUDE_ADAPTER = ('\nClaude adapter: return directly to the assigning session using actual native returns; '
                  'do not invent Codex collaboration tools. No child agents.\n')
TRANSPORT_ADAPTER = ('\n## Claude runtime\n\nThe Claude session is the DM. It may run these steps itself with the '
                     '`mcp__agentify-desktop__*` tools or dispatch `hmasd-pro-transport` (Sonnet) with the message, '
                     'conversation URL, subject key, repository, branch, source_sha, target_path, question_heading and answer_heading. '
                     'Facts return to the session, which reads the complete answer.\n')

# Shared role bodies use runtime-neutral responsibilities; native differences are appended.


def adapt_skill(text, name):
    if name == 'hmasd-chatgpt-pro-transport':
        text += TRANSPORT_ADAPTER
    return text


def generated(root=ROOT):
    outputs = {}
    for folder in sorted((root/'.agents/skills').glob('hmasd-*')):
        for source in sorted(folder.rglob('*')):
            if not source.is_file() or '__pycache__' in source.parts:
                continue
            target = root/'.claude/skills'/source.relative_to(root/'.agents/skills')
            data = source.read_bytes()
            if source.suffix in {'.md', '.py', '.yaml', '.yml', '.json', '.toml'}:
                data = data.replace(b'\r\n', b'\n')
            if source.name == 'SKILL.md':
                text = adapt_skill(data.decode('utf-8'), folder.name)
                head, body = text.split('---', 2)[1:]
                data = ('---'+head+'---\n\n'+BANNER+body.lstrip()).encode()
            outputs[target] = data
    for native, shared in ROLE_MAP.items():
        target = root/'.claude/agents'/f'{native}.md'
        header = target.read_text(encoding='utf-8').split('---', 2)[1]
        body = tomllib.loads((root/'.codex/agents'/f'{shared}.toml').read_text(encoding='utf-8'))['developer_instructions']
        adapter = CLAUDE_ADAPTER
        if native == 'hmasd-experiment-tracker':
            adapter += 'Observe one bounded window; return adoption/terminal evidence and pending notice state. The session resumes a later window; no standing polling service.\n'
        outputs[target] = ('---'+header+'---\n\n'+BANNER+body+adapter).encode()
    dm = tomllib.loads((root/'.codex/agents/hmasd-direction-manager.toml').read_text(encoding='utf-8'))['developer_instructions']
    outputs[root/'.claude/skills/hmasd-research-hub/SKILL.md'] = (f'''---
name: hmasd-research-hub
description: Drive one direction as the Claude DM under {CONSTITUTION}; not for status or mechanical edits.
---

''' + BANNER + f'The Claude session is the DM for one direction at a time under `{CONSTITUTION}`; there is no Root/DM '
    'split on this runtime. The session may implement, launch and observe directly; hmasd-implementer, '
    'hmasd-experiment-operator and hmasd-experiment-tracker are optional assistance.\n\n## Direction ownership\n\n' + dm).encode()
    transport = outputs[root/'.claude/skills/hmasd-chatgpt-pro-transport/SKILL.md'].decode()
    transport = transport.replace('name: hmasd-chatgpt-pro-transport', 'name: hmasd-pro-transport', 1)
    # Alias includes the full method; reference paths resolve to the generated canonical copy.
    transport = transport.replace('(references/', '(../hmasd-chatgpt-pro-transport/references/')
    outputs[root/'.claude/skills/hmasd-pro-transport/SKILL.md'] = transport.encode()
    return outputs


def unexpected_outputs(root, expected):
    """Report extra HMASD outputs; never delete a file or touch other publishers' trees."""
    found = set()
    for folder in (root/'.claude/skills').glob('hmasd-*'):
        for path in folder.rglob('*'):
            if (path.is_file() and '__pycache__' not in path.parts
                    and path.suffix not in {'.pyc', '.pyo'}):
                found.add(path)
    found.update(p for p in (root/'.claude/agents').glob('hmasd-*.md') if p.is_file())
    return sorted(found - set(expected))


def publish(root=ROOT, check=False):
    expected = generated(root)
    drift = []
    for path, data in expected.items():
        if not path.exists() or path.read_bytes() != data:
            drift.append(path.relative_to(root).as_posix())
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(data)
    # Extra files used to disappear from --check's view. Report them in both modes,
    # leaving archival/deletion and any active writer to the actual owner.
    drift.extend(path.relative_to(root).as_posix() for path in unexpected_outputs(root, expected))
    return sorted(set(drift))


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    changes = publish(check=args.check)
    print(('drift: ' if args.check else 'published: ') + str(len(changes)))
    remaining = changes if args.check else publish(check=True)
    if remaining:
        print('\n'.join(remaining))
        raise SystemExit(1)
