"""Publish deterministic Claude copies; development command, never a launch gate."""
from pathlib import Path
import argparse
import tomllib

ROOT = Path(__file__).resolve().parents[1]
ROLE_MAP = {
 'hmasd-reviewer':'hmasd-reviewer', 'hmasd-cm-scout':'hmasd-scout',
 'hmasd-research-scout':'hmasd-scout', 'hmasd-verifier':'hmasd-verifier',
 'hmasd-research-critic':'hmasd-research-critic',
 'hmasd-experiment-operator':'hmasd-experiment-operator',
 'hmasd-experiment-tracker':'hmasd-experiment-monitor',
 'hmasd-pro-transport':'hmasd-transport',
}
BANNER = '<!-- Generated by tools/publish_claude_control.py; edit shared source, not this body. -->\n'

CLAUDE_TRANSPORT_ADAPTER = """
## Claude publication and Transport adapter

For an authorized Claude request, use the existing CALLER_DIRECT renderer metadata
mode with owner_execution_instruction citing the actual standing Claude-transport
instruction and this assignment. It is routing metadata, not hub permission to Send.
Derive one UUID5 with uuid.uuid5(uuid.NAMESPACE_URL, actual Claude session URL), use it
for source_thread_id and parent_thread_id, and record derivation in DISPATCH_RECORD.json.
Do not fabricate a session URL or a Codex child ID. If the native identity is unavailable,
return the missing metadata; do not change accepted bindings. Supply github_delivery,
full commit_or_ref and conversation_id when already bound. Use Python 3.11+ for renderer.
Commit/push TASK, then bind with only --bind-task-sha and --handoff-path (no rendering
arguments), commit/push bound HANDOFF; CALLER_READY is the expected dispatch state.
Hub dispatches the exact handoff to its native Sonnet hmasd-pro-transport and records the
actual child identity separately. No followup_task/native_transport.py route is invented
for this runtime. Transport reads fixed HANDOFF/TASK/manifest, validates identity and
same-request state, then uses the shared Agentify effect/observation/archive procedure.
Hub does not operate Agentify itself. Bounded phases return operation/handle/effect and
full archive facts to hub; hub resumes the same agent through available native tools.
No background polling service, repeated Send, or new request on uncertain acceptance.
After verified full GitHub delivery and confirmed owned-tab closure, the existing
.agents/skills/hmasd-chatgpt-pro-transport/scripts/archive_delivered_claude_request.py
advances the exact request to ARCHIVED with its validated transitions; --help supplies
artifact/paired-ID/time arguments. Never invoke it to fabricate missing IDs, closure,
GitHub delivery or a chat fallback. Bind-only DIRECTION_VERIFIED is not archival.
Return exact full bytes/provenance and unresolved gaps directly to hub for intake.
"""

def adapt_claude_method(text, name):
    if name == 'hmasd-pro-research-prompt-author':
        start = text.index('For authorized dispatch')
        end = text.index('Bindings remain', start)
        text = text[:start] + CLAUDE_TRANSPORT_ADAPTER + '\n' + text[end:]
    elif name == 'hmasd-chatgpt-pro-transport':
        start = text.index('For GitHub handoffs on an existing')
        end = text.index('   Read the absolute registry', start)
        text = text[:start] + 'For Claude publication and routing use the adapter below; preserve frozen accepted metadata.\n\n' + text[end:]
        start = text.index('   `--claim-registry` makes')
        end = text.index('   Reuse the matching Agentify operation', start)
        text = text[:start] + '''   Inspect the exact binding before Send: an existing unfinished request must be this
   request, its conversation must match, and no different live executor may own it.
   The assigning hub serializes one writer per binding; unresolved ownership returns
   a writer conflict, never permission for another Send. Do not use --claim-registry:
   it belongs to the Codex helper, not this Claude route. Preserve ownership through
   failure and uncertainty. After observed successful Send, use existing
   scripts/bind_conversation.py with the observed conversation/provider/model facts,
   fixed request/prompt/reference/source/parent IDs and the actual operator identity
   (UUID5 of its actual Claude session URL), plus --observed-after-successful-send
   for first binding. The helper performs its own brief locked registry update;
   it is not a pre-Send reservation. Read --help for exact supported arguments.
   A refused bind requires same-request reconciliation, never a replacement Send.
   Release only after full archival; never hold a file lock across a browser wait.
   [State records](references/state-schema.md) preserve earlier evidence.

''' + text[end:]
        text = text.replace('The author DM owns one reusable native Luna/high leaf Transport.',
                            'The Claude hub owns one reusable native Sonnet leaf Transport.')
        text += '\n' + CLAUDE_TRANSPORT_ADAPTER
    return text

def generated(root=ROOT):
    outputs = {}
    for folder in sorted((root/'.agents/skills').glob('hmasd-*')):
        for source in sorted(folder.rglob('*')):
            if not source.is_file() or '__pycache__' in source.parts:
                continue
            target = root/'.claude/skills'/source.relative_to(root/'.agents/skills')
            data = source.read_bytes()
            if source.suffix in {'.md', '.py', '.yaml', '.yml', '.json', '.toml'}:
                data = data.replace(b'\r\n', b'\n')
            if source.name == 'SKILL.md':
                text = adapt_claude_method(data.decode('utf-8'), folder.name)
                head, body = text.split('---', 2)[1:]
                data = ('---'+head+'---\n\n'+BANNER+body.lstrip()).encode()
            outputs[target] = data
    for native, shared in ROLE_MAP.items():
        target = root/'.claude/agents'/f'{native}.md'
        header = target.read_text(encoding='utf-8').split('---', 2)[1]
        body = tomllib.loads((root/'.codex/agents'/f'{shared}.toml').read_text(encoding='utf-8'))['developer_instructions']
        if native == 'hmasd-experiment-operator':
            body = body.replace('DM and monitor canonical addresses', 'assigning hub return identity')
            start = body.index('After acceptance send MONITOR_ADD')
            end = body.index('A pre-process failure', start)
            body = body[:start] + "After actual acceptance return exact node/handle/source/cwd/output and observation bound to hub. The hub dispatches its bounded tracker; do not use sibling messaging, create a tracker, or keep polling after returning. Preserve collection responsibility for a later assigned terminal collection batch.\n\n" + body[end:]
        elif native == 'hmasd-experiment-tracker':
            body = body.replace('send MONITOR_ADOPTED directly to DM', 'return MONITOR_ADOPTED facts to hub')
            body = body.replace('Send MONITOR_TERMINAL or MONITOR_BLOCKER directly to DM:', 'Return MONITOR_TERMINAL or MONITOR_BLOCKER to hub:')
            body = body.replace('Reuse through followup_task for later handles.', 'Hub may resume a bounded observation window for later handles.')
        adapter = '\nClaude adapter: return directly to the assigning hub using actual native returns; do not invent Codex collaboration tools. No child agents.\n'
        if native == 'hmasd-experiment-tracker':
            adapter += 'Observe one bounded window; return adoption/terminal evidence and pending notice state. Hub resumes a later window; no standing polling service.\n'
        header = header.replace('and collects terminal outputs and receipts to their local paths', 'and returns terminal evidence to the hub for assigned collection')
        outputs[target] = ('---'+header+'---\n\n'+BANNER+body+adapter).encode()
    loop = outputs[root/'.claude/skills/hmasd-loop-dispatch/SKILL.md'].decode().split('---',2)[2]
    dm = tomllib.loads((root/'.codex/agents/hmasd-direction-manager.toml').read_text(encoding='utf-8'))['developer_instructions']
    start = dm.index('Create/reuse one monitor for accepted handles')
    end = dm.index('Terminal facts return directly', start)
    dm = dm[:start] + 'Operator returns the accepted handle to hub. Hub dispatches its bounded tracker with exact handle/node/source/output and observation limit. The tracker first return is adoption evidence; hub assigns subsequent bounded windows and terminal collection. No sibling messaging or simultaneous operator polling. ' + dm[end:]
    outputs[root/'.claude/skills/hmasd-research-hub/SKILL.md'] = ('''---
name: hmasd-research-hub
description: Drive one direction as the Claude DM under docs/project/OPERATING_CONSTITUTION.md; not for status or mechanical edits.
---

'''+BANNER+'The Claude session is the DM for one direction at a time; docs/project/OPERATING_CONSTITUTION.md prevails over any approved-set, lane, slot or ledger wording below. Only Operator launches. Use actual native task returns and bounded tracker windows; Codex tool names below describe counterpart routing, not available Claude APIs.\n\n'+loop+'\n## Direction ownership\n'+dm).encode()
    transport = outputs[root/'.claude/skills/hmasd-chatgpt-pro-transport/SKILL.md'].decode()
    transport = transport.replace('name: hmasd-chatgpt-pro-transport','name: hmasd-pro-transport',1)
    # Alias includes full method; helper/reference paths resolve to generated canonical copy.
    transport = transport.replace('(references/', '(../hmasd-chatgpt-pro-transport/references/').replace('`scripts/', '`../hmasd-chatgpt-pro-transport/scripts/')
    outputs[root/'.claude/skills/hmasd-pro-transport/SKILL.md'] = transport.encode()
    return outputs

def publish(root=ROOT, check=False):
    drift = []
    for path, data in generated(root).items():
        if not path.exists() or path.read_bytes() != data:
            drift.append(path.relative_to(root).as_posix())
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(data)
    return drift

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    changes = publish(check=args.check)
    print(('drift: ' if args.check else 'published: ') + str(len(changes)))
    if args.check and changes:
        print('\n'.join(changes))
        raise SystemExit(1)
